### ISSUE TITLE
Global minor mode overwrites face rules

### ISSUE THREAD

**Issue by gopar** [cpitclaudel/compact-docstrings#1]
Hey,

Awesome package :)

Found some undesired behavior when enabling the global minor mode 
```lisp
(add-hook 'after-init-hook #'global-compact-docstrings-mode)
```
After global minor mode is enabled, do `M-x eww`, enter a search engine (or any site that has an input box to see issue more clearly). After `eww` loads, the input boxs are invisible, looks like `compact-docstrings` is overwriting whatever faces were there before.

Easy fix is just enable in `prog-mode`
```lisp
(add-hook 'prog-mode-hook #'compact-docstrings-mode)
```

**Comment by cpitclaudel** [comment]
> Easy fix is just enable in `prog-mode`

I do that too :) 

> After global minor mode is enabled, do M-x eww, enter a search engine (or any site that has an input box to see issue more clearly). After eww loads, the input boxs are invisible, looks like compact-docstrings is overwriting whatever faces were there before.

Thanks! I think I won't have time to look at this very soon, but I'd love to merge a patch if there's an easy fix.

**Comment by gopar** [comment]
For some weird reason, I had an old version of this package (weird that I was never prompted to upgrade pkg?)

Anywho, apparently I had a version before this [old commit](https://github.com/cpitclaudel/compact-docstrings/commit/9f346d03398a15fd81c4ec507ccaa65389142310)

**Comment by gopar** [comment]
Actually, it looks like the package never got updated on [gnu elpa](https://elpa.gnu.org/packages/compact-docstrings.html).
Not sure what would need to happen to get latest changes there.

**Comment by cpitclaudel** [comment]
Thanks, I bumped the version number and pushed to GNU/ELPA; please ping me in 24 hours if doesn't appear there?

**Comment by gopar** [comment]
Sweet, got the latest update.

Thanks! :)
