### ISSUE TITLE
Lines don't get any shorter

### ISSUE THREAD

**Issue by ntevenhere** [cpitclaudel/compact-docstrings#5]
Font face is applied but blank lines don't decrease in height.
![image](https://user-images.githubusercontent.com/66701832/173255756-3b96c520-42ae-495c-91ae-f7da902f06b9.png)
![image](https://user-images.githubusercontent.com/66701832/173256156-c2a4e61e-538f-491e-b3b6-2079f749de93.png)

Loading up `emacs -Q` doesn't have the same issue so I'm bewildered. 
![image](https://user-images.githubusercontent.com/66701832/173256166-52cc353d-50dc-478f-8a9b-fc3b7da114a6.png)

I hope this is an easy aha fix but at the same time I hope it isn't, so I don't look like a fool making pointless issues like #4. 😅  Is there a variable (probably `face` related) that I can post to diagnose problems in my emacs state? It's not that scaling face height doesn't work at all, it just doesn't work for scaling down.

**Comment by cpitclaudel** [comment]
Presumably it's the line numbers?

**Comment by ntevenhere** [comment]
> Presumably it's the line numbers?

Yeah that was it. So line numbers need to be disabled for this to work. Unless we could instruct emacs to skip line numbers for empty lines. I use `display-line-numbers` which is notably inflexible (but it's fast!). But linum has `linum-format` that someone could look into.
